const Menu = [
    {
        id:1,
        image:"images/allupakoida.jpg",
        name:"Allu Pakoda",
        category:"Breakfast",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:2,
        image:"images/chola.jpg",
        name:"Chola",
        category:"Lunch",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:3,
        image:"images/corn.jpg",
        name:"Corn",
        category:"Evening",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:4,
        image:"images/maggi.jpg",
        name:"maggi",
        category:"Breakfast",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:5,
        image:"images/momo.jpg",
        name:"Momos",
        category:"Evening",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:6,
        image:"images/nonvegthali.jpg",
        name:"Nonveg Thali",
        category:"Dinner",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:7,
        image:"images/pavbhaji.jpg",
        name:"Pav Bhaji",
        category:"Evening",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:8,
        image:"images/pizza.jpg",
        name:"Pizza",
        category:"Evening",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:9,
        image:"images/puri.jpg",
        name:"Puri",
        category:"Lunch",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:10,
        image:"images/rajmarice.jpg",
        name:"Rajma Rice",
        category:"Lunch",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:11,
        image:"images/rotiwithmeat.jpg",
        name:"Roti with Meat",
        category:"Dinner",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:12,
        image:"images/samosa.jpg",
        name:"Samosa",
        category:"Breakfast",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:13,
        image:"images/sweet.jpg",
        name:"Sweet",
        category:"Evening",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    {
        id:14,
        image:"images/VadaPav.jpg",
        name:"VadaPav",
        category:"Breakfast",
        price:20,
        desription:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere non consequatur atque ad. Sed repellat sapiente dignissimos vel, nemo eveniet!",
    },
    
]
export default Menu;